name: basecalling2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools=1.21
  - bioconda::chopper=0.9.1
  - conda-forge::pigz=2.8
  - pip
  - pip:
      - pod5==0.3.23
variables:
  PATH: "/opt/dorado:$PATH"
